### ISSUE TITLE
Error uploading data

### ISSUE THREAD

**Issue by martyclark** [qgiscloud/qgis-cloud-plugin#14]
Hi,

I'm a big fan of this plugin and have been experimenting with it lately. I deleted a database this morning and attempted to create a new one and upload some new data. I successfully created the database but when I attempt to upload the data I get this error:

An error has occured while executing Python code:

Traceback (most recent call last):
  File "/home/blueman/.qgis2/python/plugins/qgiscloud/qgiscloudplugindialog.py", line 575, in upload_data
    if not self.db_connections.isPortOpen(db_name):
  File "/home/blueman/.qgis2/python/plugins/qgiscloud/db_connections.py", line 89, in isPortOpen
    if not uri.port():
AttributeError: 'NoneType' object has no attribute 'port'

I've tried un and reinstalling the plugin, restarting QGIS etc. Same error message. Any ideas what might be happening?

Thanks in advance.

Marty

edit: I'm using QGIS 2.4 on Ubuntu 14.04

**Comment by mngisguy** [comment]
I am having the exact same issue!

error happens on QGIS 2.6, 2.8.1 & 2.8.2
Windows 7
