### ISSUE TITLE
No module named ogr

### ISSUE THREAD

**Issue by Andre-J** [qgiscloud/qgis-cloud-plugin#16]
Trying to install the plugin on Windows XP or 7 with the current QGIS 2.6.1, I get the following error message:
Die Erweiterung ist defekt. Python sagte:
No module named ogr

Strange thing is that version 0.11.11 from the git repository installs without any complaint (until I update to the current version)

See also http://gis.stackexchange.com/questions/125152/no-module-named-ogr-when-installing-qgis-plugins

On Ubuntu 14.04 the latest plugin installs without complaints too. I am not sure if this has to be fixed on QGIS or the plugin side.

**Comment by pka** [comment]
Fixed in Plugion version 0.11.18
