### ISSUE TITLE
QGisCloud server does not support Cross-Origin Resource Sharing

### ISSUE THREAD

**Issue by FrankVanHam** [qgiscloud/qgis-cloud-plugin#22]
Hi there,
the server http://wms.qgiscloud.com does not support CORS, so modern browsers will refuse the requests like WFS requests.
We get errors like:
XMLHttpRequest cannot load http://wms.qgiscloud.com/blabla?service=WFS. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://195.24.73.38' is therefore not allowed access.

Could you add the Access-Control-Allow-Origin header to the responses of the server so that we can all can continue enjoying the services.

**Comment by pka** [comment]
We've activated CORS headers for all qgiscloud services. Could you please test and reopen the ticket, if an additional header is needed.
