### ISSUE TITLE
Anmeldung fehlgeschlagen: Connection to server failed: <urlopen error [Errno 11004] getaddrinfo failed>

### ISSUE THREAD

**Issue by 4minus** [qgiscloud/qgis-cloud-plugin#23]
It seems i have some proxy config issues:
When trying to sign in to qgis cloud, i get an error message:
"Connection to server failed: <urlopen error [Errno 11004] getaddrinfo failed>". The proxy configuration can't be completely wrong, since i was able to download the qgis cloud plugin from the add-on repository, and since i am able to use openstreetmap layers from the osm plugin :)

I use QGIS Essen in my corporate network behind a http proxy.

Any ideas? Thanks!
Marius

**Comment by hdus** [comment]
Please send your questions to support@qgiscloud.com
