### ISSUE TITLE
GeoTIFF broken after upload

### ISSUE THREAD

**Issue by cumarin** [qgiscloud/qgis-cloud-plugin#24]
See screenshots:

![01](https://cloud.githubusercontent.com/assets/13084242/26776206/8e40e518-49d8-11e7-8c82-2937fa406d1d.jpg)
![02](https://cloud.githubusercontent.com/assets/13084242/26776207/8e482ecc-49d8-11e7-9fd8-895dd9c93732.jpg)

File info:

* © OpenStreetMap
* EPSG: 3857
* 2976 x 2104 Pixel
* 609,8 kB (609.777 Bytes)

[tiff.zip](https://github.com/qgiscloud/qgis-cloud-plugin/files/1051463/tiff.zip)

**Comment by hdus** [comment]
This issue is fixed with the latest release.
