### ISSUE TITLE
Uploading a GeoTIFF file takes ages

### ISSUE THREAD

**Issue by cumarin** [qgiscloud/qgis-cloud-plugin#25]
[tiff.zip](https://github.com/qgiscloud/qgis-cloud-plugin/files/1051836/tiff.zip)
Uploading a GeoTiff file (609,8 kB) using the QGIS Cloud plugin takes around 8 minutes.

Steps to reproduce:

* open a new QGIS file
* add the attached GeoTIFF file
* connect to the QGIS Cloud
* create a database
* upload the GeoTIFF layer

**Comment by hdus** [comment]
With the latest release of the QGIS Cloud plugin the upload takes less than one minute.
