### ISSUE TITLE
QGIS crasches after uploading a GeoTIFF layer

### ISSUE THREAD

**Issue by cumarin** [qgiscloud/qgis-cloud-plugin#26]
[tiff.zip](https://github.com/qgiscloud/qgis-cloud-plugin/files/1051907/tiff.zip)
After uploading a GeoTiff file using the QGIS Cloud plugin, QGIS (2.18.9, Ubuntu 16.4 LTS) crashes when zooming or panning the map. The saved QGIS file is also broken. 

Steps to reproduce:

* Open a new QGIS file
* Add the attached GeoTiff file
* Upload the layer
* Save the QGIS file
* Zoom or pan the map

**Comment by hdus** [comment]
With QGIS 2.18.13 and the latest QGIS CLoud plugin release fixed.
