### ISSUE TITLE
No module named ui_qgiscloudplugin

### ISSUE THREAD

**Issue by tschuettenberg** [qgiscloud/qgis-cloud-plugin#27]
Just updated to 1.5.1 and got this message on QGIS 2.18.13 (osgeo4w 64):

Diese Erweiterung ist defekt
No module named ui_qgiscloudplugin

accordingly the QGIS Cloud menu/button disappeared.

**Comment by hdus** [comment]
Der Bug ist gefixt. Bitte upgrade auf 1.5.2 und Bericht, ob es funktioniert. Danke

**Comment by tschuettenberg** [comment]
UI is back and active again, 
allerdings steht auf Registerkarte "Über" noch "plugin-Version 1.4.17

Den Map Manager verstehe ich noch nicht, "Laden" einer Karte tut nichts außer Sanduhr (auf Werkzeugleisten-Header). 
Kann aber nicht aussschließen, dass dies am hiesigen Netzwerk liegt; teste auch heute Abend mit echtem Internet.

**Comment by hdus** [comment]
Erzwinge nochmal einen download über den Plugin-Manager dann passt auch die Version im "Über".

**Comment by tschuettenberg** [comment]
ja, Version ist jetzt korrekt.

**Comment by hdus** [comment]
Mit Version 1.5.3 sollte auch die Laden-Funktion unter Windows laufen.

**Comment by tschuettenberg** [comment]
funktioniert! cool, danke!
