### ISSUE TITLE
WMTS cascading not allowed?

### ISSUE THREAD

**Issue by rduivenvoorde** [qgiscloud/qgis-cloud-plugin#28]
Hi,

I tested QGIS Cloud by using a QGIS project file which has 5 (scale dependent) layers which are from the national WMTS services. You can donwload it from:
http://www.qgis.nl/media/2017/11/toprasters.zip

I added (and uploaded) a epsg:28992 vector province layer too to see we are ok. But still I do not see the raster/wmts layers. 

This should be the published map:
https://qgiscloud.com/rduivenvoorde/toprasters

Do I try to do something which is not allowed? Or cannot work?

No stress, just trying out, and this was the first project file I had :-)

**Comment by hdus** [comment]
Hi Richard

WMTS Cascading is allowed and should work. Trying your project and it doesn't work for me too. I have two remarcs:

1. Please activate the OTF for the project
2. When I reload the layers from the national data source again, it works fine. Both from browser as well as with WMS connector. But my connection string looks different than yours.

How did you load the WMTS?

Stay well 
Horst
