### ISSUE TITLE
Suggestion: Allow removal of layers

### ISSUE THREAD

**Issue by Saijin-Naib** [qgiscloud/qgis-cloud-plugin#37]
When attempting to publish data from a project, all layers are selected to upload (which is fine). However, I would like the option to remove some layers at the time of publish without first modifying the original project.

For instance, in the below image, I'd like to be able to delete the two highlighted layer entries from the upload list.
![image](https://user-images.githubusercontent.com/19295950/67100517-ccca3f00-f18d-11e9-9816-13fc3240750a.png)

**Comment by hdus** [comment]
Checkbox to select whether to upload a layer or not is introduced in this release. Please install and test the attached ZIP.

[qgiscloud.zip](https://github.com/qgiscloud/qgis-cloud-plugin/files/8251580/qgiscloud.zip)

**Comment by HusseinKabbout** [comment]
The problem with this, is that the layers would be broken in the uploaded project. Layers in QGIS Cloud projects must either be PG layers or WMS layers. Local datasources are not supported.
