### ISSUE TITLE
Suggestion: Allow upload/fetch of referenced fonts

### ISSUE THREAD

**Issue by Saijin-Naib** [qgiscloud/qgis-cloud-plugin#39]
I am making use of a system-installed font, Segoe UI Emoji, to use as a Font marker source as in the below image:
![image](https://user-images.githubusercontent.com/19295950/67101739-33505c80-f190-11e9-8748-7f8c261368d2.png)

Upon upload to QGIS Cloud, the project renders incorrectly as the listed font is not available, nor has an appropriate substitution font been made available ([OpenMoji?](https://github.com/hfg-gmuend/openmoji/
))

**Comment by HusseinKabbout** [comment]
Uploading your own fonts to QGIS Cloud is currently not supported and it is also not planned for the future. We will re-open this ticket if something changes.
