### ISSUE TITLE
It's not very smooth to use

### ISSUE THREAD

**Issue by wanghai1988** [qgiscloud/qgis-cloud-plugin#40]
It's not very smooth to use. Maybe it's because the server is not in China. Can we consider setting up a server in China?

**Comment by tpo** [comment]
Hi,

since the issue is not a problem of qgis-cloud-plugin per se, but of the connectivity of the QGIS Cloud service: may I ask you to please file a correponding issue at QGIS Cloud support: https://qgiscloud.com/ -> FAQ -> Open a New Ticket?

Thanks,
*t
