### ISSUE TITLE
Error uploading to QGISCloud

### ISSUE THREAD

**Issue by frankdemden** [qgiscloud/qgis-cloud-plugin#41]
I am getting the following error when attempting to upload data to QGISCLoud using QGIS 3.10:

local variable 'hexstr' referenced before assignment

Full error log below:

Traceback (most recent call last):
  File "C:/Users/Frank/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgiscloud\qgiscloudplugindialog.py", line 975, in upload_data
    self.data_upload.upload(self.db_connections.db(unicode(db_name)), data_sources_items, unicode(self.maxSize))
  File "C:/Users/Frank/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgiscloud\data_upload.py", line 254, in upload
    RasterUpload(conn,  cursor,  raster_to_upload,  maxSize,  self.progress_label)
  File "C:/Users/Frank/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgiscloud\raster\raster_upload.py", line 113, in __init__
    gt = self.wkblify_raster(opts,  infile.replace( '\\', '/') , i, gt)
  File "C:/Users/Frank/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgiscloud\raster\raster_upload.py", line 720, in wkblify_raster
    summary = self.wkblify_raster_level(options, ds, options['overview_level'], band_range, infile, i)
  File "C:/Users/Frank/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgiscloud\raster\raster_upload.py", line 666, in wkblify_raster_level
    hexwkb += self.wkblify_band_header(options, band)
  File "C:/Users/Frank/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgiscloud\raster\raster_upload.py", line 561, in wkblify_band_header
    hexwkb += self.wkblify(self.pt2fmt(pixtype), nodata)
  File "C:/Users/Frank/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgiscloud\raster\raster_upload.py", line 494, in wkblify
    return hexstr
UnboundLocalError: local variable 'hexstr' referenced before assignment

**Comment by HusseinKabbout** [comment]
@frankdemden Is it possible for you to provide the data you tried the upload with?

**Comment by frankdemden** [comment]
These are the layers I was trying to upload.

Frank D’Emden
AgTech Manager
[cid:image004.jpg@01D62519.64F4E730]2 Maxwell Street
PO Box 335
York, Western Australia 6302
P (08) 9641 2845 M 0488 917 871
E frank@livingfarm.com.au<mailto:frank@livingfarm.com.au> W www.livingfarm.com.au<http://www.livingfarm.com.au/>

IMPORTANT: This message, including any attachments, is intended only for the person or entity to which it is addressed. It may contain private or confidential information. If you think you may not be the intended recipient, or if you have received this message in error, please contact the sender immediately and delete all copies of this message. If you are not the intended recipient, you must not reproduce any part of this message or disclose its contents to any other party.

**Comment by kabbohus** [comment]
@frankdemden I already made a PR #42 that fixes this issue

**Comment by HusseinKabbout** [comment]
@frankdemden I already created a PR (#42), that should fix this issue

**Comment by HusseinKabbout** [comment]
@frankdemden Are you still encountering this error message?

**Comment by HusseinKabbout** [comment]
I will close this issue, because the problem should be fixed with my latest PR. @frankdemden If you encounter this problem again, then please reopen this issue.

**Comment by frankdemden** [comment]
Hi Hussein,
Sorry I haven’t had a chance to retest this, hopefully your fix works. Thanks for looking into this.
Cheers,
Frank.

Frank D’Emden
AgTech Manager
[cid:image004.jpg@01D6456B.427FB050]2 Maxwell Street
PO Box 335
York, Western Australia 6302
P (08) 9641 2845 M 0488 917 871
E frank@livingfarm.com.au<mailto:frank@livingfarm.com.au> W www.livingfarm.com.au<http://www.livingfarm.com.au/>

IMPORTANT: This message, including any attachments, is intended only for the person or entity to which it is addressed. It may contain private or confidential information. If you think you may not be the intended recipient, or if you have received this message in error, please contact the sender immediately and delete all copies of this message. If you are not the intended recipient, you must not reproduce any part of this message or disclose its contents to any other party.
