### ISSUE TITLE
Confirmation email doesn't come

### ISSUE THREAD

**Issue by Krukarius** [qgiscloud/qgis-cloud-plugin#46]
I've signed up and never received the confirmation email.
I've sent the confirmation request twice afterwards with no answer at all.

Could anyone advise what to do?

**Comment by tpo** [comment]
Hi @Krukarius , could you send an email directly to me tpo at sourcepole.ch and tell me which email address you have used to register? Being part of the sysadmin team I'll have a look what happened to your registration email.

Thanks!
*t

**Comment by tpo** [comment]
Ah... just in case, your email to me wouldn't come throught either, then please drop me just the domain part of your email address here in this ticket and I'll scan our logs for it. Thanks! *t

**Comment by Krukarius** [comment]
@gmail.com

**Comment by Krukarius** [comment]
you can pick up the email from my GitHub profile

**Comment by tpo** [comment]
I've replied directly to your email. Did you get it?

> you can pick up the email from my GitHub profile

This is what I see [here](https://github.com/Krukarius):

![image](https://user-images.githubusercontent.com/247241/96622497-4d280080-130a-11eb-855e-6bebfd18cf6e.png)

No email address of yours visible as far as I can tell?

**Comment by Krukarius** [comment]
Hello Tomas,

Thanks for the clarification.

Obviously, I haven't checked the Spam folder, because all stuff like this
used to come for the main box.
Nevertheless thank you very much for your help.

I saw two messages today at 12:31, so I've confirmed registration
successfully.

Sorry for bothering you then.

Best regards,

Mariusz

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Wolny
od wirusów. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
