### ISSUE TITLE
Cannot include Geotiff map in my project

### ISSUE THREAD

**Issue by Krukarius** [qgiscloud/qgis-cloud-plugin#47]
My project requires the separate map canvas (Ordnance Survey) with geotiff files.

I can't use them in my map, as the tool asks me to replace these files.

https://imgur.com/BI2LaRu

Could anyone help me to solve this problem?

I need these layers in my map. Is it possible to have a raster layer as an output, since it has been successfully loaded into database?

**Comment by tpo** [comment]
Hello @Krukarius ,

could you please file your problem at https://support.qgiscloud.com? Please check the "Knowledgebase" section there as well!

I'm closing this ticket and referring you to support@qgiscloud.com. I hope that is OK with you.

Thanks,
*t
