### ISSUE TITLE
Access to serveur problem

### ISSUE THREAD

**Issue by tsil21** [qgiscloud/qgis-cloud-plugin#50]
Please help me 
I can't upload my database, apparently I couldnot connect to the right serveur. I got this message :

could not connect to server: Connection timed out (0x0000274C/10060)
Is the server running on host "db.qgiscloud.com" (136.243.87.197) and accepting
TCP/IP connections on port 5432?

Note that the serveur address is https://api.qgiscloudcom

Thank you
All the best

**Comment by tpo** [comment]
IP and port are correct. However https://api.qgiscloudcom is wrong. Correct would be https://api.qgiscloud.com (mind the dot!).

Please take further support questions about qgiscloud to https://support.qgiscloud.com/

**Comment by tsil21** [comment]
Thank you
Best regard
Tsilavina

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

De : Tomáš Pospíšek<mailto:notifications@github.com>
Envoyé le :lundi 18 janvier 2021 22:10
À : qgiscloud/qgis-cloud-plugin<mailto:qgis-cloud-plugin@noreply.github.com>
Cc : tsil21<mailto:tsil21@hotmail.com>; Author<mailto:author@noreply.github.com>
Objet :Re: [qgiscloud/qgis-cloud-plugin] Access to serveur problem (#50)


IP and port are correct. However https://api.qgiscloudcom is wrong. Correct would be https://api.qgiscloud.com (mind the dot!).

Please take further support questions about qgiscloud to https://support.qgiscloud.com/
