### ISSUE TITLE
Suggestion: Differentiated configuration of WMS

### ISSUE THREAD

**Issue by partas1982** [qgiscloud/qgis-cloud-plugin#56]
Since more ond more datadata is available as WMS, it would be very desirable if WMS services integrated into QGIS Cloud could be configured either as a background map or as a layer.

**Comment by hdus** [comment]
You can configure these settings in the QGIS Cloud Backend on qgiscloud.com in the Maps menu. If you open the map settings of the desired map, you can select the option "External WMS layers". Then the WMS will be loaded as background layer.

**Comment by partas1982** [comment]
I should be more precise: In the QGIS Cloud backend it is possible to load external WMS as background layers. This setting then applies to all integrated WMS. But I think that this setting should be configured for each WMS / group of WMS.
Problem: External WMS, for example with aerial photos and others with factual data like antenna locations or neophytes . I do not want the factual data WMS to be displayed as a background layer.

**Comment by hdus** [comment]
With QGIS Cloud Pro you can also load external WMS WFS or WMTS layers into the map. Under Layers & Legend you will find the option “Import Layer”. Enter the URL of the desired service there in the form:

http://wms.example.com?Service=WMS&Request=GetCapabilities

If you now click on Connect, all the layers offered by the service will appear. After selecting a service, it will be added to the map. To make this setting persistent for this map, you must save the page as a bookmark in your browser. Whenever you open this bookmark later, the map will be reloaded with exactly this setting.
