### ISSUE TITLE
 Calculated fields are transfered as new fields in the Qgiscloud table

### ISSUE THREAD

**Issue by Amphibitus** [qgiscloud/qgis-cloud-plugin#58]
After transferring a new table to Qgiscloud Postgis database, the calculated fields from qgis are transferred to new fields of Qgiscloud table and the calculation is lost in QGIS

Fields before Transfer
![grafik](https://user-images.githubusercontent.com/7237786/177523980-bf9fff5b-e461-476b-95f9-04c324b08e1e.png)

Fields after Transfer

![grafik](https://user-images.githubusercontent.com/7237786/177524106-dde5bae5-b6ee-405a-bb75-1c9d0d1e4fc6.png)

**Comment by tpo** [comment]
No feedback here. I assume this ticket was fixed and am closing this ticket.
