### ISSUE TITLE
Password characters

### ISSUE THREAD

**Issue by andre-kotze** [qgiscloud/qgis-cloud-plugin#63]
Great Plugin. However, I have created a password on qgiscloud.com that contains an Umlaut (ä to be specific) but has no issues logging in, from anywhere, on the website. When I use the same password in the Plugin it refuses to log in and simply says "Wrong username or password". Easily fixed by changing the password, but it would be nice if qgiscloud.com and QGIS Cloud Plugin had the same password capabilities, or at least if the error message were more informative. Happened on Linux Mint and Windows 11, QGIS 3.28 and 3.30, Plugin version 3.8.5

**Comment by hdus** [comment]
Fixed in Rev 3.8.6
