### ISSUE TITLE
QGIS Cloud Plugin - German version?

### ISSUE THREAD

**Issue by ralfWessels** [qgiscloud/qgis-cloud-plugin#65]
Hi, I have been using the QGIS Cloud plugin again today for some time and realized that the interface is now in English. How can I restore the German interface? I am using QGIS 3.28.13 and the latest plugin version 3.9.2.
Best Greetings
Ralf

**Comment by HusseinKabbout** [comment]
In what language is your QGIS? Normally the plugin is in the language, in which QGIS is in.

**Comment by ralfWessels** [comment]
My QGIS language depends on System locale, this is german (see Screenshot) 
![Screenshot 2024-01-23 130234](https://github.com/qgiscloud/qgis-cloud-plugin/assets/52887287/cebe71e8-4564-4650-8d32-5228cad7257b)
